### ISSUE TITLE
intersection-observer-test.html multiple tests failing

### ISSUE THREAD

**Issue by cooervo** [w3c/IntersectionObserver#270]
First of all thanks for the great work and making JS better everday :+1: , step by step to my issue:

1) I downloaded this repo
2) run on chrome intersection-observer-test.html file
3) The following tests fail:
Image:
![image](https://user-images.githubusercontent.com/11219268/32948047-270c22a2-cb9e-11e7-914b-4c8b833e6598.png)

Code:
```observes multiple targets at multiple thresholds correctly ‣
Error: Script error. (:0)
    at uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.5.3/mocha.min.js:1:978)
handles rootMargin properly ‣
Error: Script error. (:0)
    at uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.5.3/mocha.min.js:1:978)
handles targets on the boundary of root ‣
Error: Script error. (:0)
    at uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.5.3/mocha.min.js:1:978)

...

handles target elements not yet added to the DOM ‣
Error: Script error. (:0)
    at uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.5.3/mocha.min.js:1:978)

...

uses the viewport when no root is specified ‣
Error: Script error. (:0)
    at uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/2.5.3/mocha.min.js:1:978)
```

I'm using the polyfill and it seems to be working for my use case, should I be worried about this failing tests?

**Comment by philipwalton** [comment]
I think these failures all represent browser bugs. For example, the test for elements not yet added to the DOM fails in Chrome, and here's the crbug for that:
https://bugs.chromium.org/p/chromium/issues/detail?id=730288

Whether you need to be worried about them depends on your usage needs I guess, but as long as you're testing your own code and it works in the browsers you support, the fact that these fail shouldn't be an issue.
