### ISSUE TITLE
still get window is not defined after trying typeof === 'undefined' import('intersection-observer')

### ISSUE THREAD

**Issue by balbaal** [w3c/IntersectionObserver#358]
window is not defined
ReferenceError: window is not defined
    at Object.<anonymous> (E:\projects\fox\talenttribe\node_modules\intersection-observer\intersection-observer.js:732:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.intersection-observer (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:9223:18)
    at __webpack_require__ (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:23:31)
    at Module../pages/jobs.js (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:3730:80)
    at __webpack_require__ (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:23:31)
    at Object.4 (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:8947:18)
    at __webpack_require__ (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:23:31)
    at module.exports.../credentials.js.module.exports.EMAIL.ADDRESS (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:91:18)
    at Object.<anonymous> (E:\projects\fox\talenttribe\src\.next\server\static\development\pages\jobs.js:94:10)

**Comment by balbaal** [comment]
![Screenshot (49)](https://user-images.githubusercontent.com/20864870/57352122-8e683700-718e-11e9-92b5-133c090e5306.png)

**Comment by crabkiller** [comment]
Perhaps you may want `typeof window !== 'undefined'` instead?

**Comment by philipwalton** [comment]
Try using version `0.7.0` and see if it fixes your issue.

**Comment by miketaylr** [comment]
Given there are a few suggestions on how to fix this, and it's been a while... I propose we close this. Please leave a comment or re-open if there's something still actionable here.
